//
//  SeamlyTokens.swift
//  Seamly — design system tokens, ported from design-system/tokens/*.css
//
//  Direction: Paper. Generated by hand from the CSS token set; keep the two in
//  step. Values that do NOT map cleanly are called out in FEASIBILITY.md rather
//  than silently approximated here.
//

import SwiftUI
#if canImport(UIKit)
import UIKit
#endif

// MARK: - Colour

extension Color {
    /// Tokens are theme-dependent, so each resolves against the trait environment
    /// rather than being a fixed value. In production these belong in an asset
    /// catalog; this initialiser keeps the port self-contained.
    nonisolated static func seamly(light: UInt32, dark: UInt32) -> Color {
        #if canImport(UIKit)
        return Color(UIColor { traits in
            UIColor(rgb: traits.userInterfaceStyle == .dark ? dark : light)
        })
        #else
        return Color(rgb: light)
        #endif
    }

    /// Like `seamly(light:dark:)` but with a per-theme alpha, for the washes — whose opacity
    /// is itself part of the contrast solve and is not the same in both themes.
    nonisolated static func seamlyAlpha(light: (UInt32, Double), dark: (UInt32, Double)) -> Color {
        #if canImport(UIKit)
        return Color(UIColor { traits in
            let (rgb, alpha) = traits.userInterfaceStyle == .dark ? dark : light
            return UIColor(rgb: rgb).withAlphaComponent(alpha)
        })
        #else
        return Color(rgb: light.0).opacity(light.1)
        #endif
    }

    nonisolated init(rgb: UInt32) {
        self.init(
            .sRGB,
            red: Double((rgb >> 16) & 0xFF) / 255,
            green: Double((rgb >> 8) & 0xFF) / 255,
            blue: Double(rgb & 0xFF) / 255,
            opacity: 1
        )
    }
}

#if canImport(UIKit)
private extension UIColor {
    nonisolated convenience init(rgb: UInt32) {
        self.init(
            red: CGFloat((rgb >> 16) & 0xFF) / 255,
            green: CGFloat((rgb >> 8) & 0xFF) / 255,
            blue: CGFloat(rgb & 0xFF) / 255,
            alpha: 1
        )
    }
}
#endif

nonisolated enum SeamlyColor {
    // Ground — warm uncoated stock; night desk darkens the desk, not the page.
    static let paper       = Color.seamly(light: 0xECE9E3, dark: 0x1A1815)
    static let paperSunk   = Color.seamly(light: 0xE3DFD8, dark: 0x131110)
    static let paperRaised = Color.seamly(light: 0xF4F2EE, dark: 0x24211D)

    /// A capture has its own brightness and must never be dimmed, so the sheet is
    /// white in BOTH themes. Do not replace this with a semantic background.
    static let sheet = Color(rgb: 0xFFFFFF)

    // Ink
    static let ink        = Color.seamly(light: 0x1F1D1A, dark: 0xF2EFE9)
    static let inkMuted   = Color.seamly(light: 0x55514B, dark: 0xA49D93)
    static let inkFaint   = Color.seamly(light: 0x6D6962, dark: 0x878075)
    static let inkInverse = Color.seamly(light: 0xF6F4F0, dark: 0x1F1D1A)

    // One accent — bookbinder's blue
    static let accent      = Color.seamly(light: 0x33456B, dark: 0x93A6D4)
    static let accentHover = Color.seamly(light: 0x253352, dark: 0xB0BFE4)

    /// The wash behind a selected finding row and the position scale's viewport bracket.
    static let accentWash = Color.seamlyAlpha(light: (0x33456B, 0.09), dark: (0x93A6D4, 0.14))

    // Marks — one per kind of doubt. Never colour alone; always paired with text.
    static let markOK    = Color.seamly(light: 0x3E6B4F, dark: 0x6FAE86)
    static let markFlag  = Color.seamly(light: 0x8A6219, dark: 0xD9A544)
    static let markGap   = Color.seamly(light: 0xA6482A, dark: 0xD9754E)
    static let markError = Color.seamly(light: 0xA3302B, dark: 0xD9615A)

    /// iOS system red for the live broadcast indicator. Never restyle.
    static let markRec = Color(rgb: 0xFF3B30)

    // Washes — status fills behind ink. Alpha differs by theme, so these resolve
    // through seamlyAlpha rather than a single opacity applied to the mark colour.
    static let washOK    = Color.seamlyAlpha(light: (0x3E6B4F, 0.10), dark: (0x6FAE86, 0.14))
    static let washFlag  = Color.seamlyAlpha(light: (0x8A6219, 0.13), dark: (0xD9A544, 0.16))
    static let washGap   = Color.seamlyAlpha(light: (0xA6482A, 0.11), dark: (0xD9754E, 0.15))
    static let washError = Color.seamlyAlpha(light: (0xA3302B, 0.10), dark: (0xD9615A, 0.14))

    // Rules — a document is ruled, not shadowed. Alpha differs by theme.
    static let rule       = Color.seamlyAlpha(light: (0x1F1D1A, 0.14), dark: (0xF2EFE9, 0.16))
    static let ruleStrong = Color.seamlyAlpha(light: (0x1F1D1A, 0.30), dark: (0xF2EFE9, 0.32))
    static let ruleFaint  = Color.seamlyAlpha(light: (0x1F1D1A, 0.07), dark: (0xF2EFE9, 0.08))

    /// NOT theme-varying, unlike the rules above. This draws a join ON THE SHEET, and the
    /// sheet is fixed white in both themes — so the ink must not flip either. colors.css:46
    /// defines it once in `:root` with no dark override, deliberately.
    static let seamConfident = Color(rgb: 0x1F1D1A).opacity(0.10)
    static let seamFlag      = markFlag
    static let seamGap       = markGap
}

// MARK: - Type
//
// The ladder IS Apple's, so every role maps to a text style and inherits Dynamic
// Type for free. Never hard-code a point size for body copy.

nonisolated enum SeamlyFont {
    static let largeTitle  = Font.largeTitle.weight(.bold)
    static let title2      = Font.title2.weight(.semibold)
    static let title3      = Font.title3.weight(.semibold)
    static let headline    = Font.headline
    static let body        = Font.body
    static let subheadline = Font.subheadline
    static let footnote    = Font.footnote
    static let caption     = Font.caption.weight(.medium)
    static let caps        = Font.caption2.weight(.semibold)

    /// Every measurement. Monospaced digits so a stepping value never reflows.
    static let mono   = Font.footnote.monospacedDigit()
    static let monoLG = Font.callout.monospacedDigit()
}

extension View {
    /// Display tracking. Absolute points, so it does not scale with Dynamic Type —
    /// acceptable at display sizes only. See FEASIBILITY.md.
    func seamlyDisplayTracking() -> some View { tracking(-0.5) }
    func seamlyCapsTracking() -> some View { tracking(0.8) }

    /// CSS `line-height` is a MULTIPLIER; `.lineSpacing()` is additive leading in points.
    /// Porting the number directly is wrong at every size and worse as Dynamic Type scales,
    /// so compute the points from the style's own resolved size. See FEASIBILITY.md.
    func seamlyLeading(_ multiplier: CGFloat, for style: UIFont.TextStyle) -> some View {
        lineSpacing((multiplier - 1) * UIFont.preferredFont(forTextStyle: style).pointSize)
    }
}

// MARK: - Space, radii, depth

nonisolated enum SeamlySpace {
    static let s1: CGFloat = 2
    static let s2: CGFloat = 4
    static let s3: CGFloat = 8
    static let s4: CGFloat = 12
    static let s5: CGFloat = 16
    static let s6: CGFloat = 20
    static let s7: CGFloat = 24
    static let s8: CGFloat = 32
    static let s9: CGFloat = 40
    static let s10: CGFloat = 48
    static let s11: CGFloat = 64

    /// A document has margins — wider than a typical iOS gutter, deliberately.
    static let gutterCompact: CGFloat = 20
    static let gutterRegular: CGFloat = 32

    /// The margin that carries the numbered markers, and the scale opposite it.
    static let marginRail: CGFloat = 34
    static let scaleRail: CGFloat = 16

    /// A 1024pt-wide capture button is absurd; the column stops here.
    static let columnMax: CGFloat = 440
    static let sidebarWidth: CGFloat = 340
    static let hitMin: CGFloat = 44

    /// How a join is drawn on the sheet. Deliberately thin — findability is the margin's job.
    static let seamWidth: CGFloat = 1
    static let seamWidthMark: CGFloat = 1.5
}

nonisolated enum SeamlyRadius {
    /// Sheets are square. Rounding is for controls only.
    static let sheet: CGFloat = 0
    static let xs: CGFloat = 3
    static let sm: CGFloat = 6
    static let md: CGFloat = 10
    static let lg: CGFloat = 14
    static let pill: CGFloat = 999
}

extension View {
    /// iOS continuous curvature, which `cornerRadius(_:)` does not give you.
    func seamlyCorners(_ r: CGFloat) -> some View {
        clipShape(RoundedRectangle(cornerRadius: r, style: .continuous))
    }

    /// Depth is a rule plus a lifted edge — paper, not glass.
    func seamlySheetLift() -> some View {
        shadow(color: .black.opacity(0.16), radius: 12, x: 0, y: 6)
            .overlay(
                Rectangle().strokeBorder(SeamlyColor.rule, lineWidth: 1)
            )
    }

    /// Chrome over a capture of unknown brightness sits on a gradient, never a
    /// flat scrim — a scrim dims content the user is trying to read.
    func seamlyProtectTop(_ height: CGFloat = 96) -> some View {
        overlay(alignment: .top) {
            LinearGradient(
                colors: [SeamlyColor.paper.opacity(0.94), SeamlyColor.paper.opacity(0)],
                startPoint: .top, endPoint: .bottom
            )
            .frame(height: height)
            .allowsHitTesting(false)
        }
    }

    /// The bottom counterpart of `seamlyProtectTop`. A gradient, never a flat scrim — a
    /// capture can be any brightness and a scrim dims what the user is reading.
    func seamlyProtectBottom(_ height: CGFloat = 96) -> some View {
        overlay(alignment: .bottom) {
            LinearGradient(
                colors: [SeamlyColor.paper.opacity(0), SeamlyColor.paper.opacity(0.94)],
                startPoint: .top, endPoint: .bottom
            )
            .frame(height: height)
            .allowsHitTesting(false)
        }
    }
}

// MARK: - Size class
//
// Layout responds to the size class, NOT to a width in points. The CSS
// breakpoints are a web stand-in; on iOS the environment already answers this,
// and it answers correctly for Split View and Stage Manager.

nonisolated struct SeamlyLayout {
    let horizontal: UserInterfaceSizeClass?
    let vertical: UserInterfaceSizeClass?

    init(horizontal: UserInterfaceSizeClass?, vertical: UserInterfaceSizeClass?) {
        self.horizontal = horizontal
        self.vertical = vertical
    }

    /// Regular width: Review gains its persistent findings rail; Library becomes
    /// a grid of uniform 3:5 cells.
    var isRegular: Bool { horizontal == .regular }

    /// Short viewport (landscape iPhone): the position scale goes horizontal,
    /// because a vertical one would eat the little height there is.
    var isShort: Bool { vertical == .compact }

    var gutter: CGFloat {
        isRegular ? SeamlySpace.gutterRegular : SeamlySpace.gutterCompact
    }
}

extension View {
    /// Never smaller than 44pt, whatever the glyph inside.
    func seamlyHitTarget() -> some View {
        frame(minWidth: SeamlySpace.hitMin, minHeight: SeamlySpace.hitMin)
    }
}

// MARK: - Motion
//
// Restrained: the main object is a 15 000 px image someone is trying to read. Ported from
// design-system/tokens/motion.css; reduce-motion is handled by SwiftUI's own accessibility
// behaviour plus `SeamlyMotion.jump`'s single use site.

nonisolated enum SeamlyMotion {
    static let press = Animation.timingCurve(0.32, 0.72, 0, 1, duration: 0.12)
    static let base = Animation.timingCurve(0.32, 0.72, 0, 1, duration: 0.22)
    /// The pan that jumps to a mark — the one that matters.
    static let jump = Animation.timingCurve(0.22, 1, 0.36, 1, duration: 0.42)
    static let stitching = Animation.timingCurve(0.32, 0.72, 0, 1, duration: 1.1)
    static let disabledOpacity: Double = 0.38
}

// MARK: - Numbers
//
// Numbers carry their unit and are separated with a thin space, never a comma —
// a comma reads as a decimal separator in much of the world.

nonisolated enum SeamlyNumber {
    static let formatter: NumberFormatter = {
        let f = NumberFormatter()
        f.numberStyle = .decimal
        f.groupingSeparator = "\u{2009}"   // thin space
        f.groupingSize = 3
        return f
    }()

    /// Just the grouped digits, no unit. The entry point for a measurement whose unit is not
    /// "px" — without it, callers hand-format and silently lose the thin space.
    static func grouped(_ value: Int) -> String {
        formatter.string(from: NSNumber(value: value)) ?? String(value)
    }

    static func px(_ value: Int) -> String {
        grouped(value) + " px"
    }

    /// e.g. "884 × 15 402 px"
    static func dimensions(width: Int, height: Int) -> String {
        let w = formatter.string(from: NSNumber(value: width)) ?? String(width)
        return "\(w) × \(px(height))"
    }
}
