//
//  SeamlyTokens.swift
//  Seamly — design system tokens, ported from design-system/tokens/*.css
//
//  Direction: Paper. Generated by hand from the CSS token set; keep the two in
//  step. Values that do NOT map cleanly are called out in FEASIBILITY.md rather
//  than silently approximated here.
//

import SwiftUI
#if canImport(UIKit)
import UIKit
#endif

// MARK: - Colour

public extension Color {
    /// Tokens are theme-dependent, so each resolves against the trait environment
    /// rather than being a fixed value. In production these belong in an asset
    /// catalog; this initialiser keeps the port self-contained.
    static func seamly(light: UInt32, dark: UInt32) -> Color {
        #if canImport(UIKit)
        return Color(UIColor { traits in
            UIColor(rgb: traits.userInterfaceStyle == .dark ? dark : light)
        })
        #else
        return Color(rgb: light)
        #endif
    }

    init(rgb: UInt32) {
        self.init(
            .sRGB,
            red: Double((rgb >> 16) & 0xFF) / 255,
            green: Double((rgb >> 8) & 0xFF) / 255,
            blue: Double(rgb & 0xFF) / 255,
            opacity: 1
        )
    }
}

#if canImport(UIKit)
private extension UIColor {
    convenience init(rgb: UInt32) {
        self.init(
            red: CGFloat((rgb >> 16) & 0xFF) / 255,
            green: CGFloat((rgb >> 8) & 0xFF) / 255,
            blue: CGFloat(rgb & 0xFF) / 255,
            alpha: 1
        )
    }
}
#endif

public enum SeamlyColor {
    // Ground — warm uncoated stock; night desk darkens the desk, not the page.
    public static let paper       = Color.seamly(light: 0xECE9E3, dark: 0x1A1815)
    public static let paperSunk   = Color.seamly(light: 0xE3DFD8, dark: 0x131110)
    public static let paperRaised = Color.seamly(light: 0xF4F2EE, dark: 0x24211D)

    /// A capture has its own brightness and must never be dimmed, so the sheet is
    /// white in BOTH themes. Do not replace this with a semantic background.
    public static let sheet = Color(rgb: 0xFFFFFF)

    // Ink
    public static let ink        = Color.seamly(light: 0x1F1D1A, dark: 0xF2EFE9)
    public static let inkMuted   = Color.seamly(light: 0x55514B, dark: 0xA49D93)
    public static let inkFaint   = Color.seamly(light: 0x6D6962, dark: 0x878075)
    public static let inkInverse = Color.seamly(light: 0xF6F4F0, dark: 0x1F1D1A)

    // One accent — bookbinder's blue
    public static let accent      = Color.seamly(light: 0x33456B, dark: 0x93A6D4)
    public static let accentHover = Color.seamly(light: 0x253352, dark: 0xB0BFE4)

    // Marks — one per kind of doubt. Never colour alone; always paired with text.
    public static let markOK    = Color.seamly(light: 0x3E6B4F, dark: 0x6FAE86)
    public static let markFlag  = Color.seamly(light: 0x8A6219, dark: 0xD9A544)
    public static let markGap   = Color.seamly(light: 0xA6482A, dark: 0xD9754E)
    public static let markError = Color.seamly(light: 0xA3302B, dark: 0xD9615A)

    /// iOS system red for the live broadcast indicator. Never restyle.
    public static let markRec = Color(rgb: 0xFF3B30)

    // Washes — status fills behind ink
    public static let washOK    = markOK.opacity(0.10)
    public static let washFlag  = markFlag.opacity(0.12)
    public static let washGap   = markGap.opacity(0.11)
    public static let washError = markError.opacity(0.10)

    // Rules — a document is ruled, not shadowed
    public static let rule       = Color.seamly(light: 0x1F1D1A, dark: 0xF2EFE9).opacity(0.14)
    public static let ruleStrong = Color.seamly(light: 0x1F1D1A, dark: 0xF2EFE9).opacity(0.30)
    public static let ruleFaint  = Color.seamly(light: 0x1F1D1A, dark: 0xF2EFE9).opacity(0.07)

    /// How a join is drawn on the sheet. Deliberately quiet — findability is the
    /// margin's job, not this line's.
    public static let seamConfident = Color.seamly(light: 0x1F1D1A, dark: 0xF2EFE9).opacity(0.10)
    public static let seamFlag      = markFlag
    public static let seamGap       = markGap
}

// MARK: - Type
//
// The ladder IS Apple's, so every role maps to a text style and inherits Dynamic
// Type for free. Never hard-code a point size for body copy.

public enum SeamlyFont {
    public static let largeTitle  = Font.largeTitle.weight(.bold)
    public static let title2      = Font.title2.weight(.semibold)
    public static let title3      = Font.title3.weight(.semibold)
    public static let headline    = Font.headline
    public static let body        = Font.body
    public static let subheadline = Font.subheadline
    public static let footnote    = Font.footnote
    public static let caption     = Font.caption.weight(.medium)
    public static let caps        = Font.caption2.weight(.semibold)

    /// Every measurement. Monospaced digits so a stepping value never reflows.
    public static let mono   = Font.footnote.monospacedDigit()
    public static let monoLG = Font.callout.monospacedDigit()
}

public extension View {
    /// Display tracking. Absolute points, so it does not scale with Dynamic Type —
    /// acceptable at display sizes only. See FEASIBILITY.md.
    func seamlyDisplayTracking() -> some View { tracking(-0.5) }
    func seamlyCapsTracking() -> some View { tracking(0.8) }
}

// MARK: - Space, radii, depth

public enum SeamlySpace {
    public static let s1: CGFloat = 2
    public static let s2: CGFloat = 4
    public static let s3: CGFloat = 8
    public static let s4: CGFloat = 12
    public static let s5: CGFloat = 16
    public static let s6: CGFloat = 20
    public static let s7: CGFloat = 24
    public static let s8: CGFloat = 32
    public static let s9: CGFloat = 40
    public static let s10: CGFloat = 48
    public static let s11: CGFloat = 64

    /// A document has margins — wider than a typical iOS gutter, deliberately.
    public static let gutterCompact: CGFloat = 20
    public static let gutterRegular: CGFloat = 32

    /// The margin that carries the numbered markers, and the scale opposite it.
    public static let marginRail: CGFloat = 34
    public static let scaleRail: CGFloat = 16

    /// A 1024pt-wide capture button is absurd; the column stops here.
    public static let columnMax: CGFloat = 440
    public static let sidebarWidth: CGFloat = 340
    public static let hitMin: CGFloat = 44
}

public enum SeamlyRadius {
    /// Sheets are square. Rounding is for controls only.
    public static let sheet: CGFloat = 0
    public static let xs: CGFloat = 3
    public static let sm: CGFloat = 6
    public static let md: CGFloat = 10
    public static let lg: CGFloat = 14
    public static let pill: CGFloat = 999
}

public extension View {
    /// iOS continuous curvature, which `cornerRadius(_:)` does not give you.
    func seamlyCorners(_ r: CGFloat) -> some View {
        clipShape(RoundedRectangle(cornerRadius: r, style: .continuous))
    }

    /// Depth is a rule plus a lifted edge — paper, not glass.
    func seamlySheetLift() -> some View {
        shadow(color: .black.opacity(0.16), radius: 12, x: 0, y: 6)
            .overlay(
                Rectangle().strokeBorder(SeamlyColor.rule, lineWidth: 1)
            )
    }

    /// Chrome over a capture of unknown brightness sits on a gradient, never a
    /// flat scrim — a scrim dims content the user is trying to read.
    func seamlyProtectTop(_ height: CGFloat = 96) -> some View {
        overlay(alignment: .top) {
            LinearGradient(
                colors: [SeamlyColor.paper.opacity(0.94), SeamlyColor.paper.opacity(0)],
                startPoint: .top, endPoint: .bottom
            )
            .frame(height: height)
            .allowsHitTesting(false)
        }
    }
}

// MARK: - Size class
//
// Layout responds to the size class, NOT to a width in points. The CSS
// breakpoints are a web stand-in; on iOS the environment already answers this,
// and it answers correctly for Split View and Stage Manager.

public struct SeamlyLayout {
    public let horizontal: UserInterfaceSizeClass?
    public let vertical: UserInterfaceSizeClass?

    public init(horizontal: UserInterfaceSizeClass?, vertical: UserInterfaceSizeClass?) {
        self.horizontal = horizontal
        self.vertical = vertical
    }

    /// Regular width: Review gains its persistent findings rail; Library becomes
    /// a grid of uniform 3:5 cells.
    public var isRegular: Bool { horizontal == .regular }

    /// Short viewport (landscape iPhone): the position scale goes horizontal,
    /// because a vertical one would eat the little height there is.
    public var isShort: Bool { vertical == .compact }

    public var gutter: CGFloat {
        isRegular ? SeamlySpace.gutterRegular : SeamlySpace.gutterCompact
    }
}

public extension View {
    /// Never smaller than 44pt, whatever the glyph inside.
    func seamlyHitTarget() -> some View {
        frame(minWidth: SeamlySpace.hitMin, minHeight: SeamlySpace.hitMin)
    }
}

// MARK: - Numbers
//
// Numbers carry their unit and are separated with a thin space, never a comma —
// a comma reads as a decimal separator in much of the world.

public enum SeamlyNumber {
    public static let formatter: NumberFormatter = {
        let f = NumberFormatter()
        f.numberStyle = .decimal
        f.groupingSeparator = "\u{2009}"   // thin space
        f.groupingSize = 3
        return f
    }()

    public static func px(_ value: Int) -> String {
        (formatter.string(from: NSNumber(value: value)) ?? String(value)) + " px"
    }

    /// e.g. "884 × 15 402 px"
    public static func dimensions(width: Int, height: Int) -> String {
        let w = formatter.string(from: NSNumber(value: width)) ?? String(width)
        return "\(w) × \(px(height))"
    }
}
